version: "3"
services:
  postgres:
    image: "postgres:14-alpine"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    restart: always
